plugins {
    id 'java'
    id 'org.jetbrains.gradle.plugin.idea-ext' version '1.3'
    id 'com.azuredoom.hytale-tools' version '1.0.38'
}

hytaleTools {
    manifestGroup = 'org.MoreMagicSpell'
    // Author format: Name, or Name|Email, or Name|Email|Url.
    // Separate multiple authors with commas. Email and Url are optional.
    // Example: 'Alice|alice@example.com|https://example.com,Bob'
    modCredits = 'Im404,Rirpod'
    patchline = 'release'
    modId = 'More_Magic_Spell'
    mainClass = 'org.MoreMagicSpell.MoreMagicSpell'

    // Optional: enabled by default. Injects hosted Hytale API docs into
    // generated Vineflower server sources for easier IDE browsing.
    injectServerJavadocsIntoSources = true
}  