# The group ID used for maven publishing. Usually the same as your package name
# but not the same as your plugin group!
maven_group=org.MoreMagicSpell


# Gradle
org.gradle.daemon                    = true
org.gradle.jvmargs                   = -Xmx3G
org.gradle.parallel                  = true
org.gradle.caching                   = true
org.gradle.java.home                 = /usr/lib/jvm/java-25-openjdk
name                                 = MoreMagicSpell

# Common
java_version                         = 25
hytale_version                       = 0.+
manifestServerVersion                = ^0.6.0
release_type                         = RELEASE
maven_url                            = https://maven.azuredoom.com/mods
hmod_maven_url                       = https://maven.hytalemodding.dev/releases

# Publishing
modtale_uuid                         = 
modifold_id                          = 
curseforgeID                         = 1451167

# Mod options
manifest_group                       = org.MoreMagicSpell
mod_name                             = More_Magic_Spell
main_class                           = org.MoreMagicSpell.MoreMagicSpell
mod_author                           = Im404,Riprod
mod_id                               = More_Magic_Spell
mod_license                          = ARR
mod_description                      = 
mod_credits                          = Im404,Riprod
mod_logo                             = icon-256.png
mod_url                              = https://modtale.net/mod/more-magic-spells
mod_issues                           = https://github.com/ImThe404/Hytale_More_Magic_Spell/issues
mod_sources                          = https://github.com/ImThe404/Hytale_More_Magic_Spell
version                              = 1.4.0
includes_pack                        = true
disabled_by_default                  = false
patchline                            = release
load_user_mods                       = false
manifest_dependencies                = 
manifest_opt_dependencies            = Riprod:Hexcode=^0.10.0,Riprod:Patchly=*